services: 
  jachobs-mind-bot:
    image: jdolakk/${PROJECT}-image
    env_file:
      - ../../.env
    restart: no
    deploy:
      resources:    
        limits:
          memory: 200MB
    volumes:
      - discorddata:/botdata

volumes:
  discorddata:
