version: '3.1'

services: 
  jachobs-mind-bot:
    image: ${PROJECT}-image
    restart: no
    deploy:
      resources:    
        limits:
          memory: 200MB
    volumes:
      - discorddata:/botdata

volumes:
  discorddata:
