pipeline {
    agent any
    environment {
       PATH="/run/current-system/sw/bin"
       DISCORD_TOKEN = credentials('DISCORD_TOKEN')
       GUILDID = credentials('GUILDID')
       APPID = credentials('APPID')
       WEBHOOKTOKEN = credentials('WEBHOOKTOKEN')
    }
    stages {
        stage("Checkout") {
            steps {
                git branch: 'main', url: 'https://github.com/jdolak/jachobs-mind-bot-2.git'
            }
        }
        stage("Setup Test Env") {
            steps {
                sh 'echo $APPID'
                sh 'mkdir ./libs || true'
                sh 'touch .env'
            }
        }
        stage("Build") {
            steps {
                sh 'make build'
            }
        }
        stage("Test") {
            steps {
                sh 'make test'
            }
        }
        stage("Deploy") {
            steps {
                //sh 'make deploy'
                sh 'echo "skipping for now"'
            }
        }
    }
    post {
        always {
            sh 'make down'
        }
    }
}